# Generated by Django 5.2.6 on 2025-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(default="unit", max_length=50)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Commodity",
                "verbose_name_plural": "Commodities",
                "ordering": ["name"],
            },
        ),
    ]
