# Generated by Django 5.2.6 on 2025-09-11 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commodity",
            old_name="current_price",
            new_name="price",
        ),
    ]
