# Generated by Django 5.2.6 on 2025-09-11 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0002_rename_current_price_commodity_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commodity",
            old_name="last_updated",
            new_name="updated_at",
        ),
    ]
