# Generated by Django 5.2.6 on 2025-09-11 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0003_rename_last_updated_commodity_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="commodity_type",
            field=models.CharField(
                choices=[
                    ("AGRICULTURE", "Agriculture"),
                    ("ENERGY", "Energy"),
                    ("METAL", "Metal"),
                    ("LIVESTOCK", "Livestock"),
                    ("ALTERNATIVE", "Alternative Asset"),
                ],
                default="ALTERNATIVE",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CommodityPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=2, max_digits=15)),
                ("high", models.DecimalField(decimal_places=2, max_digits=15)),
                ("low", models.DecimalField(decimal_places=2, max_digits=15)),
                ("close", models.DecimalField(decimal_places=2, max_digits=15)),
                ("volume", models.BigIntegerField()),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="commodities.commodity",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("commodity", "date")},
            },
        ),
    ]
