# Generated by Django 5.2.6 on 2025-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0004_commodity_commodity_type_commoditypricehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commoditypricehistory",
            name="open",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
