# Generated by Django 5.2.6 on 2025-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0005_alter_commoditypricehistory_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="commoditypricehistory",
            name="open",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
